### ISSUE TITLE
Digesting YAML objects

### ISSUE THREAD

**Issue by jondashkyle** [jondashkyle/smarkt#1]
Right now setting YAML object as a field value fails.

```
cities: 
  losangeles:
    name: Los Angeles
    country: USA
  tokyo:
    name: Tokyo
    country: Japan
```

## Todo

- [x] `stringify`
- [x] `parse`
